-- ============================================================
-- PulseTrace — ShakthiDB Schema
-- PostgreSQL 16+
-- ============================================================
-- This schema defines the core storage for system observability
-- metrics. It is designed to be:
--   • TimescaleDB-ready (timestamp-ordered tables)
--   • Partition-friendly (created_at on all tables)
--   • Extensible (JSONB columns for future fields)
-- ============================================================

-- ============================================================
-- EXTENSIONS
-- ============================================================

-- Enable UUID generation for future use (API keys, trace IDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- TABLE: system_metrics
-- ============================================================
-- One row per collection interval per host.
-- This is the primary metrics table — the heart of ShakthiDB.
-- ============================================================

CREATE TABLE IF NOT EXISTS system_metrics (
    id              BIGSERIAL       PRIMARY KEY,
    hostname        VARCHAR(255)    NOT NULL,
    collected_at    TIMESTAMPTZ     NOT NULL,

    -- CPU
    cpu_percent     DOUBLE PRECISION,
    cpu_per_core    JSONB,
    cpu_freq_mhz    DOUBLE PRECISION,

    -- Load averages
    load_avg_1      DOUBLE PRECISION,
    load_avg_5      DOUBLE PRECISION,
    load_avg_15     DOUBLE PRECISION,

    -- Memory
    memory_total    BIGINT,
    memory_used     BIGINT,
    memory_available BIGINT,
    memory_percent  DOUBLE PRECISION,
    swap_total      BIGINT,
    swap_used       BIGINT,
    swap_percent    DOUBLE PRECISION,

    -- Disk
    disk_total      BIGINT,
    disk_used       BIGINT,
    disk_free       BIGINT,
    disk_percent    DOUBLE PRECISION,
    disk_read_bytes BIGINT,
    disk_write_bytes BIGINT,

    -- Network
    net_bytes_sent  BIGINT,
    net_bytes_recv  BIGINT,
    net_packets_sent BIGINT,
    net_packets_recv BIGINT,
    net_errin       BIGINT          DEFAULT 0,
    net_errout      BIGINT          DEFAULT 0,
    net_dropin      BIGINT          DEFAULT 0,
    net_dropout     BIGINT          DEFAULT 0,

    -- Extensibility
    extra           JSONB           DEFAULT '{}',

    -- Metadata
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Primary query pattern: "show me metrics for host X in time range Y"
CREATE INDEX IF NOT EXISTS idx_system_metrics_host_time
    ON system_metrics (hostname, collected_at DESC);

-- Dashboard "latest" query optimization
CREATE INDEX IF NOT EXISTS idx_system_metrics_collected_at
    ON system_metrics (collected_at DESC);


-- ============================================================
-- TABLE: process_metrics
-- ============================================================
-- Top N processes captured at each collection interval.
-- Linked to system_metrics by hostname + timestamp.
-- ============================================================

CREATE TABLE IF NOT EXISTS process_metrics (
    id              BIGSERIAL       PRIMARY KEY,
    hostname        VARCHAR(255)    NOT NULL,
    collected_at    TIMESTAMPTZ     NOT NULL,

    pid             INTEGER         NOT NULL,
    name            VARCHAR(255),
    username        VARCHAR(255),
    status          VARCHAR(50),
    cpu_percent     DOUBLE PRECISION,
    memory_percent  DOUBLE PRECISION,
    memory_rss      BIGINT,
    num_threads     INTEGER,
    command         TEXT,

    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_process_metrics_host_time
    ON process_metrics (hostname, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_process_metrics_pid
    ON process_metrics (pid, collected_at DESC);


-- ============================================================
-- TABLE: alerts
-- ============================================================
-- Generated by the backend when thresholds are crossed, or by
-- the AI engine when anomalies are detected.
-- ============================================================

CREATE TABLE IF NOT EXISTS alerts (
    id              BIGSERIAL       PRIMARY KEY,
    hostname        VARCHAR(255)    NOT NULL,
    severity        VARCHAR(20)     NOT NULL CHECK (severity IN ('critical', 'warning', 'info')),
    category        VARCHAR(50)     NOT NULL,
    message         TEXT            NOT NULL,
    metric_value    DOUBLE PRECISION,
    threshold       DOUBLE PRECISION,
    source          VARCHAR(50)     NOT NULL DEFAULT 'rule_engine',
    resolved        BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_alerts_host_time
    ON alerts (hostname, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_unresolved
    ON alerts (resolved, created_at DESC)
    WHERE resolved = FALSE;


-- ============================================================
-- TABLE: predictions
-- ============================================================
-- AI engine outputs: anomaly scores, forecasts, root cause
-- analysis results. Phase 3 will populate this.
-- ============================================================

CREATE TABLE IF NOT EXISTS predictions (
    id              BIGSERIAL       PRIMARY KEY,
    hostname        VARCHAR(255)    NOT NULL,
    model_name      VARCHAR(100)    NOT NULL,
    prediction_type VARCHAR(50)     NOT NULL,
    category        VARCHAR(50),
    score           DOUBLE PRECISION,
    details         JSONB           DEFAULT '{}',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_predictions_host_time
    ON predictions (hostname, created_at DESC);


-- ============================================================
-- TABLE: metric_metadata
-- ============================================================
-- Agent self-registration. Each agent reports its identity
-- and capabilities on startup.
-- ============================================================

CREATE TABLE IF NOT EXISTS metric_metadata (
    id              BIGSERIAL       PRIMARY KEY,
    hostname        VARCHAR(255)    NOT NULL UNIQUE,
    os_name         VARCHAR(100),
    os_version      VARCHAR(100),
    kernel_version  VARCHAR(100),
    cpu_count       INTEGER,
    total_memory    BIGINT,
    agent_version   VARCHAR(50),
    first_seen      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    last_seen       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_metric_metadata_hostname
    ON metric_metadata (hostname);
